services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - bmpl-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bmpl-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - bmpl-network

  user-backend:
    build:
      context: ./user
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@db:3306/${DB_NAME}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bmpl-network

  admin-backend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@db:3306/${DB_NAME}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bmpl-network

  user-frontend:
    build:
      context: ./user-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=https://api-user.mindvex.cloud
    networks:
      - bmpl-network

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=https://api-admin.mindvex.cloud
    networks:
      - bmpl-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - user-frontend
      - admin-frontend
      - user-backend
      - admin-backend
    networks:
      - bmpl-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - bmpl-network

networks:
  bmpl-network:
    driver: bridge

volumes:
  bmpl-db-data:
